# Generated by Django 4.1.3 on 2023-12-14 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='科室名称')),
                ('account', models.CharField(max_length=64, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('permission_type', models.CharField(max_length=256, verbose_name='权限类型')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.CharField(max_length=32, verbose_name='性别')),
                ('education', models.CharField(max_length=32, verbose_name='学历')),
                ('academic_degree', models.CharField(max_length=32, verbose_name='学位')),
                ('major', models.CharField(max_length=32, verbose_name='专业')),
                ('graduated_school', models.CharField(max_length=32, verbose_name='毕业院校')),
                ('working_time', models.DateField(verbose_name='参加工作时间')),
                ('phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('birthday', models.DateField(verbose_name='出生年月')),
                ('surgical_qualification', models.CharField(max_length=32, verbose_name='手术资质')),
                ('surgical_qualification_1', models.BooleanField(default=False)),
                ('surgical_qualification_2', models.BooleanField(default=False)),
                ('surgical_qualification_3', models.BooleanField(default=False)),
                ('surgical_qualification_4', models.BooleanField(default=False)),
                ('surgical_qualification_certificate_pic', models.CharField(max_length=512, verbose_name='手术资质授权表')),
                ('prescription_normal', models.BooleanField(default=False)),
                ('prescription_Antibacterials_restricted', models.BooleanField(default=False)),
                ('prescription_Antibacterials_unrestricted', models.BooleanField(default=False)),
                ('prescription_Antibacterials_special', models.BooleanField(default=False)),
                ('prescription_Antineoplastic_normal', models.BooleanField(default=False)),
                ('prescription_Antineoplastic_limited', models.BooleanField(default=False)),
                ('prescription_Narcotics_Narcotic_drugs', models.BooleanField(default=False)),
                ('prescription_Narcotics_Psychotropic_first', models.BooleanField(default=False)),
                ('prescription_Narcotics_Psychotropic_second', models.BooleanField(default=False)),
                ('prescription_Corticosteroids_Short_glucocorticoid', models.BooleanField(default=False)),
                ('prescription_Corticosteroids_Long_glucocorticoid', models.BooleanField(default=False)),
                ('prescription_Biological_and_blood_preparations', models.BooleanField(default=False)),
                ('changwaiyingyangzhiji', models.BooleanField(default=False)),
                ('jizhenyongxue', models.BooleanField(default=False)),
                ('pingzhenyongxue', models.BooleanField(default=False)),
                ('yongxueliangxiaoyu800', models.BooleanField(default=False)),
                ('yongxueliangxiaoyu1600', models.BooleanField(default=False)),
                ('jianyanbaogao', models.BooleanField(default=False)),
                ('jianchabaogao', models.BooleanField(default=False)),
                ('shuxuejianyanbaogao', models.BooleanField(default=False)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.department', verbose_name='科室')),
            ],
        ),
        migrations.CreateModel(
            name='StudyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_time', models.CharField(max_length=128, verbose_name='进修时间')),
                ('study_hospital', models.CharField(max_length=64, verbose_name='进修医院')),
                ('study_major', models.CharField(max_length=64, verbose_name='进修专业')),
                ('study_certificate_pic', models.CharField(max_length=512, verbose_name='进修证照片')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='shoushuzizhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('surgical_qualification_1', models.BooleanField(default=False)),
                ('surgical_qualification_2', models.BooleanField(default=False)),
                ('surgical_qualification_3', models.BooleanField(default=False)),
                ('surgical_qualification_4', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('surgical_qualification_certificate_pic', models.CharField(max_length=512, verbose_name='手术资质授权表')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=64, verbose_name='立项时间')),
                ('start_type', models.CharField(max_length=64, verbose_name='立项类型')),
                ('title', models.CharField(max_length=64, verbose_name='题目')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_time', models.DateField(verbose_name='发表时间')),
                ('journal_name', models.CharField(max_length=64, verbose_name='期刊名称')),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('project_rank', models.CharField(max_length=64, verbose_name='项目类型')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_time', models.CharField(max_length=64, verbose_name='获奖年度')),
                ('award_rank', models.CharField(max_length=64, verbose_name='获奖级别')),
                ('award_name', models.CharField(max_length=64, verbose_name='获奖名称')),
                ('award_certificate_pic', models.CharField(max_length=512, verbose_name='获奖证书')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='职称名')),
                ('engage_time', models.DateField(verbose_name='聘任时间')),
                ('certificate_number', models.CharField(max_length=64, verbose_name='聘任时间')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='OutTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_study_time', models.DateField(verbose_name='外出学习时间')),
                ('out_study_place', models.CharField(max_length=64, verbose_name='外出学习地点')),
                ('out_study_meeting', models.CharField(max_length=64, verbose_name='学习会议名称')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='ObtainPatents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_time', models.CharField(max_length=128, verbose_name='年度')),
                ('type', models.CharField(max_length=64, verbose_name='专利类型')),
                ('name', models.CharField(max_length=64, verbose_name='专利名称')),
                ('patents_certificate_pic', models.CharField(max_length=512, verbose_name='专利证书')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='NewTechResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_time', models.DateField(verbose_name='获取开展时间')),
                ('to_nomal_time', models.DateField(verbose_name='转常规技术开展时间')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='NewTechAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='获奖年度')),
                ('award_rank', models.CharField(max_length=64, verbose_name='获奖级别')),
                ('award_name', models.CharField(max_length=64, verbose_name='获奖名称')),
                ('award_certificate_pic', models.CharField(max_length=512, verbose_name='获奖证书')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_yongxuezizhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('jizhen', models.BooleanField(default=False)),
                ('pingzhen', models.BooleanField(default=False)),
                ('xiaoyu800', models.BooleanField(default=False)),
                ('xiaoyu1600', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_shouquan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('youchuangcaozuoshouquan', models.BooleanField(default=False)),
                ('rijianshoushushouquan', models.BooleanField(default=False)),
                ('mazuishouquan', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('shouquanpic', models.CharField(max_length=512, verbose_name='相关授权表')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_shengwuyuxueyezhiji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('shengwuyuxueyezhiji', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_putongchufangquan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('putongchufangquan', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_pizhijisuleiyaowu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('duanzhongcheng', models.BooleanField(default=False)),
                ('chongjiliaofachangliaocheng', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_mazuijingshen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('mazuiyaopin', models.BooleanField(default=False)),
                ('diyileijingshenyaopin', models.BooleanField(default=False)),
                ('dierleijingshenyaopin', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_kangzhongliu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('putongshiyong', models.BooleanField(default=False)),
                ('xianzhishiyong', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_kangjunyaowu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('feixianzhi', models.BooleanField(default=False)),
                ('xianzhi', models.BooleanField(default=False)),
                ('teshujikangjunyaowu', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_changwaiyingyangzhiji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('changwaiyingyangzhiji', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
        migrations.CreateModel(
            name='chufang_baogaoqianziquan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_year', models.CharField(max_length=64, verbose_name='年度')),
                ('jianyanbaogao', models.BooleanField(default=False)),
                ('jianchabaogao', models.BooleanField(default=False)),
                ('shuxuejianyanbaogao', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=256, verbose_name='其他')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorRecordsServerApp.doctorinfo', verbose_name='医生档案主表')),
            ],
        ),
    ]
