# Generated by Django 4.1.1 on 2022-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorRecordsServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtechaward',
            name='get_year',
            field=models.CharField(max_length=64, verbose_name='获奖年度'),
        ),
        migrations.AlterField(
            model_name='researchaward',
            name='award_time',
            field=models.CharField(max_length=64, verbose_name='获奖年度'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='start_time',
            field=models.CharField(max_length=64, verbose_name='立项时间'),
        ),
    ]
