# Generated by Django 4.1.1 on 2022-10-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorRecordsServerApp', '0002_alter_newtechaward_get_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainpatents',
            name='get_time',
            field=models.CharField(max_length=128, verbose_name='年度'),
        ),
        migrations.AlterField(
            model_name='studytable',
            name='study_time',
            field=models.CharField(max_length=128, verbose_name='进修时间'),
        ),
    ]
