# Generated by Django 4.1.1 on 2022-10-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorRecordsServerApp', '0004_remove_doctorinfo_surgical_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='avatar.jpg', upload_to='photos')),
            ],
        ),
    ]
