# Generated by Django 4.1.1 on 2022-10-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorRecordsServerApp', '0005_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='surgical_qualification_certificate_pic',
            field=models.CharField(max_length=256, verbose_name='手术资质授权表'),
        ),
        migrations.AlterField(
            model_name='newtechaward',
            name='award_certificate_pic',
            field=models.CharField(max_length=256, verbose_name='获奖证书'),
        ),
        migrations.AlterField(
            model_name='obtainpatents',
            name='patents_certificate_pic',
            field=models.CharField(max_length=256, verbose_name='专利证书'),
        ),
        migrations.AlterField(
            model_name='researchaward',
            name='award_certificate_pic',
            field=models.CharField(max_length=256, verbose_name='获奖证书'),
        ),
        migrations.AlterField(
            model_name='studytable',
            name='study_certificate_pic',
            field=models.CharField(max_length=256, verbose_name='进修证照片'),
        ),
    ]
